env:
  browser: true,
  es6: true
extends: "airbnb"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
rules: {
  react/jsx-one-expression-per-line: 'off',
  react/button-has-type: 'off',
  jsx-a11y/no-noninteractive-tabindex: 'off',
  react/destructuring-assignment: [0],
  object-curly-newline: 'off',
  no-use-before-define: ["error", { "functions": false, "classes": true, "variables": true }],
  max-len: 'off',
}
