version: "3.9"
services:
  mywebapp:
    image: webapp:v1.0
    container_name: webapp
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"